version: "3.9"

services:
  #app is the name of our service, that is gonna run our docker fie
  app:
    #Its gonna build our Docker  file inside our current directory - (.) in context  
    build: 
      #Use the current directory from where weäre using our dockercompose from.
      context: .
      #This sets the DEV build argument for the app service to True during the build process
      args:
        - DEV=true 
    #Port mapping. This maps port 8000 in our local machine to port 8000 inside our Docker Container. This is how we can access the network when we want to connect to our server.
    ports:
      - "8000-8000"     
    #Mapping directories from our system to our container. We map the app directory in our project to /app in our container
    volumes:
      - ./app:/app
    image: app:django 
    container_name: my_container1
    #The command that is used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
